const actionType = {
    GET_HOME:  'GET_HOME',
    SET_CURRENT_SONG_ID: 'SET_CURRENT_SONG_ID',
    SET_CURRENT_SONG_DATA: 'SET_CURRENT_SONG_DATA',
    SET_CURRENT_ALBUM_ID: 'SET_CURRENT_ALBUM_ID',
    LOADING: 'LOADING', 
    CHECK_PLAYING : 'CHECK_PLAYING',
    CHECK_AT_ALBUM: 'CHECK_AT_ALBUM',
    GET_PLAYLIST: 'GET_PLAYLIST',
    SET_RECENT: 'SET_RECENT'

}

export default actionType