const actionType = {
    GET_HOME:  'GET_HOME',
    SET_CURRENT_SONG_ID: 'SET_CURRENT_SONG_ID',
    CHECK_PLAYING : 'CHECK_PLAYING',
    CHECK_AT_ALBUM: 'CHECK_AT_ALBUM',
    GET_PLAYLIST: 'GET_PLAYLIST'
}

export default actionType