export {default as SideBarLeft} from './SideBarLeft'
export {default as SideBarRight} from './SideBarRight'
export {default as Header} from './Header'
export {default as Slider} from './Slider'
export {default as Player} from './Player'
